# Generated by Django 4.1.7 on 2023-03-30 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("forge", "0002_alter_project_manager_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskassignment",
            name="assignee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="taskassignment",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="forge.project",
            ),
        ),
        migrations.DeleteModel(
            name="ProjectTaskAssignment",
        ),
    ]
