# Generated by Django 4.1.7 on 2023-03-31 15:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("forge", "0004_task_project"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taskassignment",
            name="project",
        ),
    ]
